<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugins [
        <!ELEMENT plugins (plugin*)>
        <!ELEMENT plugin (
                name,
                className,
                description,
                authors,
                screenshotUrl?,
                category*,
                downloadUrl?,
                version*,
                upOnlyVersion*)>
        <!ELEMENT name      (#PCDATA)>
        <!ELEMENT className      (#PCDATA)>                             <!--fully qualified class name of the plugin class. For wrapper plugins, this should be equal to the name attribute in the plugin's pluginWrapper.xml's wrapperPlugin element-->
        <!ELEMENT description    (#PCDATA)>
        <!ELEMENT authors (#PCDATA)>
        <!ELEMENT screenshotUrl    (#PCDATA)>                           <!--should be 200x140 pixels-->
        <!ELEMENT category    (#PCDATA)>                                <!--Still need to decide what these are, now we have [Assembly, Alignment, Phylogenetics, Protein, Nucleotide, Services and Searching and Misc-->
        <!ELEMENT downloadUrl (#PCDATA)>                                <!--Optional URL of a web page where the plugin can be downloaded. If the plugin is not installed the user will be sent here instead of downloading directly. Updates are always downloaded directly if plugin is already installed.-->
        <!ELEMENT version    (changes, file+)>
        <!ELEMENT upOnlyVersion    (changes, file+)>                    <!--Plugins to only upload but not promote & not show in Geneious Downloadable plugins. Mainly for experimental plugins-->
        <!ELEMENT changes (#PCDATA)>                                    <!--list of changes in this version, html tags accepted-->
        <!ELEMENT file (platform+, url)>
        <!ELEMENT url (#PCDATA)>                                        <!--URL of the gplugin file-->
        <!ELEMENT platform    (#PCDATA)>                                <!--add one of these for each platform supported by the gplugin, must be one of: All, Windows, MacOS, Linux-->

        <!ATTLIST version minimumApiVersion CDATA #REQUIRED>            <!--must be a decimal in the form x.y-->
        <!ATTLIST version maximumApiVersion CDATA #REQUIRED>            <!--must be an int-->
        <!ATTLIST version pluginVersion CDATA #REQUIRED>                <!--must be in the same form as a Geneious version number eg. x.y(.z)-->
        <!ATTLIST version releaseDate CDATA #REQUIRED>                  <!--yyyy-MM-dd format-->
        <!ATTLIST version isBeta (true|false) #REQUIRED>                <!--beta version are clearly marked as such in Geneious and users are only informed of their release if they specify they are interested in betas-->
        <!ATTLIST upOnlyVersion minimumApiVersion CDATA #REQUIRED>      <!--must be a decimal in the form x.y-->
        <!ATTLIST upOnlyVersion maximumApiVersion CDATA #REQUIRED>      <!--must be an int-->
        <!ATTLIST upOnlyVersion pluginVersion CDATA #REQUIRED>          <!--must be in the same form as a Geneious version number eg. x.y(.z)-->
        <!ATTLIST upOnlyVersion releaseDate CDATA #REQUIRED>            <!--yyyy-MM-dd format-->
        <!ATTLIST upOnlyVersion isBeta (true|false) #REQUIRED>          <!--beta version are clearly marked as such in Geneious and users are only informed of their release if they specify they are interested in betas-->
        <!ATTLIST plugin isNoteWorthy (true|false) #REQUIRED>           <!--if true, users will be notified of its release and the plugin will be displayed at the top of the list with a star next to it-->
        <!ATTLIST plugin isProOnly (true|false) #REQUIRED>
        <!ATTLIST plugin releaseDate CDATA #REQUIRED>                   <!--yyyy-MM-dd format, if the plugin has a recent release date then it will be marked as NEW in the plugin list-->
        <!ATTLIST plugin isPayFor (true|false) #IMPLIED>                <!--whether a license/trial is required in the plugin, false if not specified-->
        ]>

<plugins>
    

    <plugin isNoteWorthy="true" isProOnly="false" releaseDate="2022-02-11">
        <name>Benchling Plugin</name>
        <className>Geneious Benchling Plugin</className>
        <description>Plugin uploads selected sequences to banchling.</description>
        <authors>Ratmir Slepenkov</authors>
        <category>Integration</category>
        <version minimumApiVersion="4.202010" maximumApiVersion="4" pluginVersion="0.2.22" releaseDate="2022-04-28" isBeta="false">
            <changes>
                This plugin can be run using 'Export to Benchling' in the tool bar.
            </changes>
            <file>
                <platform>All</platform>
                <url>https://github.com/conspiratus/upddir/blob/master/BenchlingPlugin_0_2_21.gplugin?raw=true</url>
            </file>
        </version>
    </plugin>

</plugins>
